package view;

/**
 * Enumeration for menu choice.
 */
public enum UserOption {
  ADD_BOAT,
  ADD_MEMBER,
  DELETE_BOAT,
  DELETE_MEMBER,
  EDIT_BOAT,
  EDIT_BOAT_ALL,
  EDIT_BOAT_LENGTH,
  EDIT_BOAT_TYPE,
  EDIT_MEMBER,
  EDIT_MEMBER_ALL,
  EDIT_MEMBER_NAME,
  EDIT_MEMBER_PNR,
  EXIT,
  GO_BACK,
  LIST_COMPACT,
  LIST_MEMBER,
  LIST_VERBOSE,
  LOG_IN,
  LOG_OUT,
  SHOW_MEMBER_INFO,
  MENU_MAIN,
  MENU_MAIN_AUTH,
  MENU_EDIT_MEMBER,
  MENU_EDIT_BOAT,
  MENU_LIST,
  MENU_SEARCH,
  SEARCH_MEMBERS,
  SEARCH_ON_NAME,
  SEARCH_ON_BOATTYPE
}
